import { cp, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = process.cwd();
const outRoot = join(root, "build-assets");

const monacoSource = join(root, "node_modules", "monaco-editor", "min", "vs");
const monacoOut = join(outRoot, "monaco", "vs");

const monacoVimSource = join(root, "node_modules", "monaco-vim", "dist", "monaco-vim.umd.js");
const editorOut = join(outRoot, "editor");
const monacoVimOut = join(editorOut, "monaco-vim.js");

async function main() {
  await mkdir(join(outRoot, "monaco"), { recursive: true });
  await mkdir(editorOut, { recursive: true });

  await cp(monacoSource, monacoOut, { force: true, recursive: true });

  const monacoVimBundle = await readFile(monacoVimSource, "utf8");
  const wrappedMonacoVimBundle = `// Generated by scripts/build-editor-assets.ts from monaco-vim/dist/monaco-vim.umd.js.
(function () {
  const hadDefine = Object.prototype.hasOwnProperty.call(window, "define");
  const previousDefine = window.define;

  try {
    window.define = undefined;
${monacoVimBundle}
    window.ReplMonacoVim = window.MonacoVim;
  } finally {
    if (hadDefine) {
      window.define = previousDefine;
    } else {
      delete window.define;
    }
  }
})();
`;

  await writeFile(monacoVimOut, wrappedMonacoVimBundle);

  console.log(`Editor assets written to ${outRoot}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
